# Generated by Django 4.2.6 on 2023-10-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin_data',
            name='chartype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='linkedin_data',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='linkedin_data',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='linkedin_data',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='linkedin_data',
            name='prof_pic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
